### PR TITLE
Enable EPEL when installing packages on testnodes

### PR DESCRIPTION
**Pull request by zmc**
Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by dmick** [comment]
Do you want to do this regardless of the package, or only for some packages?  This seems to run the other risk of unintentional installation of something from epel.

**Comment by zmc** [comment]
Before we disalbed epel on everything, we had the same behavior you're describing. I don't think epel is even allowed to carry packages that are already in RHEL

**Comment by zmc** [comment]
But, this might break CentOS. so... I'm not sure what to do.

**Comment by ktdreyer** [comment]
The issue with EPEL wasn't really about conflicting with RHEL or CentOS itself - it was about conflicting with what we shipped in the "layered product" Red Hat Ceph Storage downstream :(

**Comment by dmick** [comment]
yeah.  We don't want to enable EPEL while installing Ceph, for instance, only some of its dependencies.

I think it would be safer to enable epel only for certain sets of packages, not globally.

**Comment by zmc** [comment]
@dmick that's actually exactly what this PR does.

It also doesn't break CentOS; it fixes it the same way it fixes RHEL. I think this would be good to merge.

**Comment by dmick** [comment]
welll....This looks like it changes the lowlevel worker such that whatever is in the packages variable is allowed to come from epel, which seems ripe for mistakes.  I would think we would want to explicitly say which packages are allowed to come from epel and which are not, such that 'packages' might be split into 'packages' and 'epel_packages' or some such at a higher level.

**Comment by andrewschoen** [comment]
@dmick I agree that's a good approach, do you know of an easy way to know know which list a package would belong in?

Also, I'd love to see teuthology tasks start installing the packages it needs instead of it being done with cm-ansible.  Honestly, I'm not even sure how many packages in that list are really needed.

The immediate need here though is to fix the testnodes role in octo where epel is disabled by default.  We can do that with this PR or by enabling epel again.  I'm hesitant to block on this for too long as octo is pretty broken without it.

**Comment by andrewschoen** [comment]
I've made a list of epel packages for rhel7 in this commit: 3e88d2b3b0c14416ac77d9026514914b9cc4c407

**Comment by zmc** [comment]
Closing in favor of #102

**Pull request closed without merging**
