### PR TITLE
all: s/include:/include_tasks:/g prepping for deprecation in v2.8

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
@djgalloway has this been tested w/ teuthology at all?

**Comment by djgalloway** [comment]
Oh good call.  Very good call.  Gimme a bit.

**Comment by djgalloway** [comment]
@zmc 
http://pulpito.ceph.com/dgalloway-2017-12-18_19:29:31-smoke-luminous-distro-basic-ovh
http://pulpito.ceph.com/dgalloway-2017-12-18_19:29:02-smoke-luminous-distro-basic-smithi
http://pulpito.ceph.com/dgalloway-2017-12-18_19:28:43-smoke-luminous-distro-basic-mira

All job failures are past the point of ceph-cm-ansible getting run successfully.

**Comment by zmc** [comment]
Awesome thank you!

**Pull request merged**
