### PR TITLE
testnodes: add opensuse 15.1 support

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@djgalloway Could you please review.
Notice: I was able to make a teuthology image using this changes in OVH and was able to successfully lock the node with `--os-type opensuse --os-version 15.1` on my teuthology setup.

**Comment by kshtsk** [comment]
Following image has been used for verification of the change:
https://download.opensuse.org/distribution/leap/15.1/jeos/openSUSE-Leap-15.1-JeOS.x86_64-15.1.0-OpenStack-Cloud-Snapshot9.166.qcow2

**Comment by djgalloway** [comment]
> Following image has been used for verification of the change:
> https://download.opensuse.org/distribution/leap/15.1/jeos/openSUSE-Leap-15.1-JeOS.x86_64-15.1.0-OpenStack-Cloud-Snapshot9.166.qcow2

Is this qcow2 already ansible-ized?  Or do you need me to create one in our OVH instance?

**Comment by kshtsk** [comment]
> > Following image has been used for verification of the change:
> > https://download.opensuse.org/distribution/leap/15.1/jeos/openSUSE-Leap-15.1-JeOS.x86_64-15.1.0-OpenStack-Cloud-Snapshot9.166.qcow2
> 
> Is this qcow2 already ansible-ized? Or do you need me to create one in our OVH instance?

No, it is not ansiblized, if I understand correctly, so it the one which should be applied following roles as described on wiki: ansible_managed, (fix the opensuse user id and owner ship), users, testnodes, like this:

```
ansible-playbook -i inventory-opensuse-15.1 -e "ansible_ssh_user=opensuse" -e @cm-user.yaml ansible_managed.yml

# the next step will/can fail with error message:
# usermod: user opensuse is currently used by process 1063non-zero return code
# this is because ansible leaves running an sshd session from previous execution
# ansible -e ansible_ssh_user=cm -i inventory-opensuse-15.1 -a "sudo ps aux | grep ^opensuse" -vvv all

ansible -e ansible_ssh_user=cm -i inventory-opensuse-15.1 -a "sudo usermod -u 2000 opensuse" all
ansible -e ansible_ssh_user=cm -i inventory-opensuse-15.1 -a "sudo chown -R opensuse: /home/opensuse" all

ansible-playbook -i inventory-opensuse-15.1 -e "ansible_ssh_user=cm" users.yml
ansible-playbook -i inventory-opensuse-15.1 -e "ansible_ssh_user=cm" testnodes.yml

```

**Comment by djgalloway** [comment]
@kshtsk do you have a Cobbler server you can use to test adding 15.1 to?  While this does allow us to run the testnodes role against an OpenSUSE 15.1 system, we need to be able to add the OS to Cobbler so we can automatically capture FOG images.

**Comment by kshtsk** [comment]
> @kshtsk do you have a Cobbler server you can use to test adding 15.1 to? While this does allow us to run the testnodes role against an OpenSUSE 15.1 system, we need to be able to add the OS to Cobbler so we can automatically capture FOG images.

No, unfortunately I have no Cobbler server.

**Pull request merged**
