### PR TITLE
A new playbook to install or remove packages

### PR DESCRIPTION
**Pull request by andrewschoen**
See: http://tracker.ceph.com/issues/13851

### CODE REVIEW

**Comment by vasukulkarni** [comment]
LGTM, thanks @andrewschoen

**Comment by zmc** [comment]
When this is run from teuthology, it looks like it will do the right thing when running in "install then remove on cleanup" mode. But will it do the right thing for "remove then reinstall on cleanup"? I can't immediately tell.

**Comment by andrewschoen** [comment]
This does not support a "remove and reinstall on cleanup" feature. I could
see that working by passing a ``remove=True`` variable that would inverse
the current logic. Is that something we need for this now?

**Comment by vasukulkarni** [comment]
@andrewschoen Its not required for now, we will still have to add the dependent packages to be removed in the main ansible cleanup logic at the beginning of the test.

**Pull request merged**
