### PR TITLE
nsupdate_web: make sure nsupdate user group exists

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
@djgalloway could you please review

**Comment by djgalloway** [comment]
The ansible `user` module uses `useradd` to create users.  By default, `useradd` will create the group unless otherwise specified.  Is that not the case on OpenSUSE?

https://www.computerhope.com/unix/useradd.htm

**Comment by kshtsk** [comment]
> The ansible `user` module uses `useradd` to create users. By default, `useradd` will create the group unless otherwise specified. Is that not the case on OpenSUSE?
> 
> https://www.computerhope.com/unix/useradd.htm

It appears that not, at least for Leap 42.3, however I can double check this for Leap 15.0 and Leap 15.1

**Comment by djgalloway** [comment]
It can't hurt anything I guess.  Was just curious.

**Pull request merged**
