### PR TITLE
testnodes: Configure cpan and install Amazon::S3 on all OSes

### PR DESCRIPTION
**Pull request by djgalloway**
Fixes: http://tracker.ceph.com/issues/15316

Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by dmick** [comment]
Did you test a run on centos?  The bug comments allege that it had been enabled but wasn't working

**Comment by djgalloway** [comment]
Yes. Tested on smithi005.  I see nothing in the git commit history indicating Amazon::S3 was ever installed on CentOS.

IOW, I found no evidence of [this](http://tracker.ceph.com/issues/15316#note-6) and [this log](http://tracker.ceph.com/issues/15316#note-7) shows it installed on smithi048, an Ubuntu node, and skipped on smithi019, a CentOS node.

This log/playbook run was after the system was provisioned using a ``-stock`` profile so only users got set up by Cobbler's ansible run.
<code>
TASK [common : Log the OS name, version and release] ***************************
ok: [smithi005.front.sepia.ceph.com] => {
    "msg": "Host smithi005.front.sepia.ceph.com is running CentOS 7.2.1511 (Core)"
}
...
TASK [testnode : include] ******************************************************
included: /home/dgalloway/git/ceph/ceph-cm-ansible/roles/testnode/tasks/cpan.yml for smithi005.front.sepia.ceph.com

TASK [testnode : Add CPAN config directory for the teuthology user.] ***********
ok: [smithi005.front.sepia.ceph.com]

TASK [testnode : Add CPAN config directory for the root user.] *****************
ok: [smithi005.front.sepia.ceph.com]

TASK [testnode : Upload CPAN config for the teuthology user.] ******************
ok: [smithi005.front.sepia.ceph.com]

TASK [testnode : Upload CPAN config for root.] *********************************
ok: [smithi005.front.sepia.ceph.com]

TASK [testnode : Ensure perl-doc is installed on apt systems.] *****************
skipping: [smithi005.front.sepia.ceph.com]

TASK [testnode : Check to see if Amazon::S3 is installed.] *********************
fatal: [smithi005.front.sepia.ceph.com]: FAILED! => {"changed": false, "cmd": ["perldoc", "-l", "Amazon::S3"], "delta": "0:00:00.076638", "end": "2016-06-27 21:43:41.203025", "failed": true, "rc": 1, "start": "2016-06-27 21:43:41.126387", "stderr": "No documentation found for \"Amazon::S3\".", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

TASK [testnode : Install Amazon::S3.] ******************************************
changed: [smithi005.front.sepia.ceph.com]
</code>

**Comment by smithfarm** [comment]
`Reviewed-by: Nathan Cutler <ncutler@suse.com>`

**Comment by zmc** [comment]
welp, next time I'll make sure to demand a full output log; I'm seeing the modules getting installed to ``~cm/perl5``, which is very much the wrong thing :(

**Pull request merged**
