### PR TITLE
Adding the releasever variable to rhel7.9 testnodes

### PR DESCRIPTION
**Pull request by akraitman**
Fixes: https://tracker.ceph.com/issues/49771

Signed-off-by: Adam Kraitman <akraitma@redhat.com>

### CODE REVIEW

**Review by djgalloway — CHANGES_REQUESTED** [review]
A few things:

- These tasks only get pulled on on RHEL so the `ansible_distribution == "RedHat"` is redundant.
- Use the `ansible_lsb.release` var and make it version-independent
- Use a module.  Maybe `copy`

```
copy:
  content: "{{ ansible_lsb.release }}"
  dest: /etc/yum/vars/releasever
```

Make sure you test this by running the entire `cephlab.yml` playbook on a RHEL7.9 and RHEL8.3 testnode.

**Comment by akraitman** [comment]
> A few things:
> 
> * These tasks only get pulled on on RHEL so the `ansible_distribution == "RedHat"` is redundant.
> * Use the `ansible_lsb.release` var and make it version-independent
> * Use a module.  Maybe `copy`
> 
> ```
> copy:
>   content: "{{ ansible_lsb.release }}"
>   dest: /etc/yum/vars/releasever
> ```
> 
> Make sure you test this by running the entire `cephlab.yml` playbook on a RHEL7.9 and RHEL8.3 testnode.

I placed it in testnode/tasks/yum/repos.yml instead since i saw it has to run before the "Install packages" task , tested on rhel7.9 and on rhel8.3

**Comment by djgalloway** [comment]
> I placed it in testnode/tasks/yum/repos.yml instead since i saw it has to run before the "Install packages" task , tested on rhel7.9 and on rhel8.3

Okay, well in that case, you will want `when: ansible_distribution == "RedHat"`.  Please also add a comment above the task explaining what it's for.

Let's try removing the `ansible_distribution_version == "7.9"` and see what happens on RHEL7.8 and RHEL8.x.

**Comment by akraitman** [comment]
> > I placed it in testnode/tasks/yum/repos.yml instead since i saw it has to run before the "Install packages" task
> 
> Okay, well in that case, you will want `when: ansible_distribution == "RedHat"`. Please also add a comment above the task explaining what it's for.
> 
> Let's try removing the `ansible_distribution_version == "7.9"` and see what happens on RHEL7.8 and RHEL8.x.

Okay, did this change and tested it on rhel7.9 and rhel8.3

**Comment by djgalloway** [comment]
Edit the comment to include the link to the tracker then we're good.

**Review by djgalloway — APPROVED** [review]

**Pull request merged**
