### PR TITLE
Skip ansible_user creation if it is undefined

### PR DESCRIPTION
**Pull request by zmc**
Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
Should we skip it or just provide sane defaults?  Either way, I think ansible_user and ansible_user_uid_ need to be added to a defaults/main.yml for this role.

**Comment by andrewschoen** [comment]
I'm gonna go ahead and merge this and we can follow up with the change to defaults.

**Comment by zmc** [comment]
@andrewschoen Didn't see your question until now, but I think either way would be fine. The inspiration for this PR was teuthology, which doesn't care about ``ansible_user`` at all.

**Comment by andrewschoen** [comment]
@zmc yeah, I'm not sure if we should provide default values or not.  But, I think these two vars should definitely be present in defaults/main.yml is all.  It's no urgent thing.

**Pull request merged**
