### PR TITLE
testnodes: Set sane warn/crit thresholds for nagios check_load

### PR DESCRIPTION
**Pull request by djgalloway**
Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
We never finished discussing what optimal thresholds would be with <code>--percpu</code> added but it probably makes sense to figure it out here for historical purposes.

irvingi06 was alerting a moment ago so here's some examples..

<pre>
### Current config
ubuntu@irvingi06:~$ /usr/lib/nagios/plugins/check_load --warning=15,10,5 --critical=30,25,20
WARNING - load average: 2.99, 4.15, 9.10|load1=2.990;15.000;30.000;0; load5=4.150;10.000;25.000;0; load15=9.100;5.000;20.000;0; 

### Proposed config
ubuntu@irvingi06:~$ /usr/lib/nagios/plugins/check_load --percpu --warning=0.7,0.6,0.5 --critical=0.9,0.8,0.7
OK - load average: 0.12, 0.17, 0.38|load1=0.121;0.700;0.900;0; load5=0.171;0.600;0.800;0; load15=0.378;0.500;0.700;0; 

### Just --percpu without changing thresholds (this will obviously never alert)
ubuntu@irvingi06:~$ /usr/lib/nagios/plugins/check_load --percpu --warning=15,10,5 --critical=30,25,20
OK - load average: 0.12, 0.17, 0.38|load1=0.118;15.000;30.000;0; load5=0.170;10.000;25.000;0; load15=0.376;5.000;20.000;0; 

ubuntu@irvingi06:~$ w
 08:58:00 up 111 days, 17:10,  1 user,  load average: 2.86, 4.04, 8.96

ubuntu@irvingi06:~$ cat /proc/cpuinfo | grep processor | wc -l
24
</pre>

So maybe <code>--warning=1.2,1.0,0.95 --critical=2.0,1.9,1.8</code>?  I'm just throwing arbitrary thresholds out at this point.

**Comment by dmick** [comment]
I say we try it.

**Comment by djgalloway** [comment]
So I'm thinking the thresholds in my previous comment may be more sane now that we've used this for a week.  We've been getting alerts for irvingi06 that its load is ~1.2 and don't really need to worry unless we're close to 2.0 IMO.  What's protocol here?  Open a new PR?

**Comment by dmick** [comment]
Bug me to pay attention.  I will.

Sent from Nine

**Pull request merged**
