### PR TITLE
pcp: update upstream packages

### PR DESCRIPTION
**Pull request by zmc**
PCP's upstream doesn't version its dependencies in all cases. This leads
to situations where, when setting upstream_repo to True, a system ends
up with some old and some new packages. This results in a potentially
broken installation.

This commit causes all installed pcp packages to be upgraded when
upstream_repo is True.

Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by dmick** [comment]
This would have been a *whole* lot less confusing if you'd mentioned "since repo.yml isn't included when upstream_repo is false, do the apt update in main.yml".  That took a long while to untangle in my head because I was looking for behavior based on upstream_repo == True.

**Comment by zmc** [comment]
sorry @dmick :(

**Comment by dmick** [comment]
Not that big of a deal, just setting levels about context :)

**Comment by djgalloway** [comment]
Context?! :smile:

**Comment by dmick** [comment]
Oh you!  (Insert meme here)

**Pull request merged**
