### PR TITLE
skip packages / repo unavailable on aarch64 

### PR DESCRIPTION
**Pull request by dachary**
And revert the change that replace hardcoded x86_64 with {{ansible_architecture}}. Although it's a good idea in theory, in practice it points to non-existent repositories.

### CODE REVIEW

**Comment by dachary** [comment]
@dmick I'm very unexperienced with ansible, please let me know if things should be done differently.

**Comment by dachary** [comment]
@dmick this has been tested to work in the context of cloudlab (see http://dachary.org/?p=3939)

**Comment by leseb** [comment]
@dachary this looks like a pretty decent way to me for separating both packages installation :+1:

**Comment by dachary** [comment]
@leseb changed as suggested, thanks !

**Comment by zmc** [comment]
@dachary was this reviewed by someone on the team? From here it looks like you just merged your own PR :-/

**Comment by dachary** [comment]
@zmc I did, indeed. Sorry about that.

**Pull request merged**
