### PR TITLE
Add the ability to revoke user accounts

### PR DESCRIPTION
**Pull request by zmc**
Signed-off-by: Zack Cerza <zack@redhat.com>

### CODE REVIEW

**Comment by andrewschoen** [comment]
This looks good.  I think we need to add the ability to filter the ``revoked_users`` list if the ``users`` var is defined.  We already allow this with ``managed_users`` and ``managed_admin_users``.

**Comment by zmc** [comment]
@andrewschoen When I try the example of filtering users from the README.rst, I get:
```
ERROR: Expecting : delimiter: line 1 column 8 (char 8)
```

**Comment by andrewschoen** [comment]
@zmc oops, typo in the docs.  try:

```
ansible-playbook users.yml -vv --limit="$NODE" --extra-vars='{"users":["user"]}'
```
I'll send a PR to fix that, unless you want to fix it here.

**Comment by zmc** [comment]
@andrewschoen yep, already found and fixed it :)

**Pull request merged**
