### PR TITLE
pcp: A dynamic dashboard with host- and time-selection

### PR DESCRIPTION
**Pull request by zmc**
The main intent for this is to provide a link to view performance stats relevant to each teuthology job.

I'm open to feedback re: the name of the dashboard.

### CODE REVIEW

**Comment by zmc** [comment]
[The usage statement](http://pcp.front.sepia.ceph.com:44323/grafana/index.html#/dashboard/script/index.js)
[An example job view](http://pcp.front.sepia.ceph.com:44323/grafana/index.html#/dashboard/script/index.js?time_to=2016-04-19T23:08:24&time_from=2016-04-19T22:44:21&hosts=vpm095,vpm101,vpm112)
[Another example job view](http://pcp.front.sepia.ceph.com:44323/grafana/index.html#/dashboard/script/index.js?time_to=2016-05-02T21:10:57&time_from=2016-05-02T21:05:49&hosts=vpm128,vpm139&title=job%2012345)

**Comment by dmick** [comment]
So I sorta think I kinda understand that this is running in a context that has at least jQuery and underscore.js available to it.  Is there documentation for creating a dashboard for grafana in JS somewhere that I'm failing to find on http://docs.grafana.org?

**Comment by dmick** [comment]
Answering my own question (thought to use google rather than rely on anyone's ability to actually design a table of contents):  Maybe http://docs.grafana.org/reference/scripting/

**Comment by zmc** [comment]
Unfortunately that link is the extent of the documentation I found.

**Comment by dmick** [comment]
There are still improvements to be made, but this is a pretty cool start.

**Pull request merged**
