### PR TITLE
Move NRPE setup to common role

### PR DESCRIPTION
**Pull request by djgalloway**
Initially tested on a single machine with CentOS, RHEL, and Ubuntu Xenial using the -stock profile.

Tested all changes by running `--tags="nagios"` against all of Octo.

### CODE REVIEW

**Comment by djgalloway** [comment]
DNM yet.  Found a bug.

**Comment by djgalloway** [comment]
Don't forget about me!

**Comment by zmc** [comment]
Sorry who are you?

**Comment by zmc** [comment]
;) Awesome docs. This looks great

**Comment by dmick** [comment]
I was totally forgetting this.  Sorry!

**Pull request merged**
