### PR TITLE
rhel package changes required for ceph

### PR DESCRIPTION
**Pull request by vasukulkarni**
Rhel packages that needs to be added or removed to satisfy dependency and work across various ceph releases without conflict, Still in testing.

### CODE REVIEW

**Comment by vasukulkarni** [comment]
Dependent on https://github.com/ceph/teuthology/pull/709

**Comment by zmc** [comment]
Will this cause problems on CentOS/Fedora? Should we make it only affect RHEL?

**Comment by zmc** [comment]
Also please tweak the commit message of the first commit so it doesn't overflow

**Comment by vasukulkarni** [comment]
@zmc: this should not create issues for centOS and fedora, it will help by removing those dependency present and if present can create conflict. I think we should do this for apt as well.

**Comment by vasukulkarni** [comment]
@zmc fixed commit messages

**Comment by andrewschoen** [comment]
@vasukulkarni would you mind rebasing this branch?

**Comment by vasukulkarni** [comment]
@andrewschoen rebased and pushed

**Comment by andrewschoen** [comment]
Do we want to do this for debian systems as well?

**Comment by vasukulkarni** [comment]
@andrewschoen debian is good, we dont have this issue on debian when i tested it.

**Pull request merged**
