### PR TITLE
Added "- ncurses-devel" for xfstests to run and pass

### PR DESCRIPTION
**Pull request by yuriw**
Fixes http://tracker.ceph.com/issues/14848

Signed-off-by: Yuri Weinstein <yweinste@redhat.com>

### CODE REVIEW

**Comment by ktdreyer** [comment]
It would be great if the particular *test* that need this package could add it instead

**Comment by ktdreyer** [comment]
Sigh, nevermind, I see that was already shot down in the Redmine ticket.

**Comment by dmick** [comment]
Yeah, I'd rather have it there, but this is not the time I suppose.  The thing is we'll never go back and clean these up.  

oh well.

**Comment by dmick** [comment]
yuriw: add a line to the commit message that says, exactly:

Fixes: #14848

just above your Signed-off-by line.

**Pull request merged**
