### PR TITLE
[DNM] testnode: support openSUSE

### PR DESCRIPTION
**Pull request by smithfarm**
This is part of my work to get teuthology-openstack to support testing on openSUSE Leap VMs.

The patches in this PR get me through the ansible.cephlab task in OVH.

### CODE REVIEW

**Comment by smithfarm** [comment]
@dmick Can you take a look?

**Comment by dmick** [comment]
I have not had time to even start to look at teuthology-openstack.  I'm afraid my review wouldn't mean much.

**Comment by smithfarm** [comment]
Changing to DNM (Do Not Merge) until I can run some suites with it in both OVH and Sepia.

**Comment by smithfarm** [comment]
@dmick It's true that teuthology-openstack is my current focus, but isn't this also relevant to http://tracker.ceph.com/issues/14683 ?

**Comment by dmick** [comment]
Not really; that's about autobuild-ceph or ceph-build

**Comment by smithfarm** [comment]
New (and tested) PR now open at #281

**Pull request closed without merging**
