### PR TITLE
testnode/tasks/apt/packages.yml: just force everything

### PR DESCRIPTION
**Pull request by athanatos**
Signed-off-by: Samuel Just <sjust@redhat.com>

### CODE REVIEW

**Comment by athanatos** [comment]
Tested: sjust@teuthology:/a/samuelj-2016-05-16_20:02:21-rados-wip-sam-testing-distro-basic-smithi/197087

**Comment by zmc** [comment]
@athanatos this makes me a little nervous. Some justification for the change would help me understand why it's necessary. Thanks!

**Comment by athanatos** [comment]
@zmc Same reason I added force elsewhere, the install failed with a message indicating that -y was used without --force.  I didn't diagnose further.

**Comment by zmc** [comment]
@athanatos that's not ringing a bell. Was it recent?

**Comment by zmc** [comment]
```
[15:25:40]  <zackc>	sjusthm: ok. so, i don't have a memory of the "same reason"
[15:26:05]  <sjusthm>	zackc: let me try to find the run
[15:29:51]  <zackc>	sjusthm: is it this pr? https://github.com/ceph/ceph-cm-ansible/pull/221
[15:30:13]  <sjusthm>	yes
[15:30:17]  <sjusthm>	found an example
[15:30:23]  <sjusthm>	sjust@teuthology:/a/samuelj-2016-05-10_19:44:43-rados-wip-split-lfn-hammer-distro-basic-smithi/183862
[15:31:53]  <zackc>	oh, package auth problem
[15:32:00]  <zackc>	was that ever root-caused?
[15:32:08]  <zackc>	it's kind of alarming
[15:32:16]  <zackc>	i vaguely remember looking into it
[15:32:28]  <sjusthm>	no, it was never root caused
[15:32:35]  <sjusthm>	I mostly just want to avoid having it mess up the tests
[15:32:50]  <sjusthm>	no reason it can't be root caused in parallel
[15:32:56]  <sjusthm>	but at least the tests will fail less often
[15:34:22]  <zackc>	yeah, i suppose you're right
```

There's no reason to block this particular PR, even though our use of ``force`` everywhere bugs me. So I'll merge :)

**Pull request merged**
