### PR TITLE
testnodes: configure selinux for nagios monitoring

### PR DESCRIPTION
**Pull request by djgalloway**
This addresses SELinux denials on CentOS and RHEL testnodes.

Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by djgalloway** [comment]
@zmc What do you think about this approach?

I've tested on mira101.  The output makes it back to nagios but isn't correct.  I've confirmed that issue's not SELinux related, however, by disabling SELinux on mira101 as a sanity check.

**Comment by zmc** [comment]
@djgalloway Looks pretty good! What's wrong with the output? Should it be tested on a smithi?

**Comment by djgalloway** [comment]
@zmc I just tested it on smithi019 and output is as expected.  The mangled output on mira101 could be anything.. May need a reimage, may just need the whole testnodes playbook re-run but I'm pretty confident it's not SELinux.
<pre>
#  Output on mira101
0 of drives failing/missing
Controller needs newer firmware for S.M.A.R.T. support
</pre>
Also found another package, <code>libsemanage-python</code> was required to use the seboolean ansible module so threw that in as an additional task in my latest push.

**Comment by zmc** [comment]
Awesome, thanks @djgalloway

**Pull request merged**
