### PR TITLE
cobbler: Output message indicating Ansible is running after firstboot

### PR DESCRIPTION
**Pull request by djgalloway**
Console output with this change looks like:

    [  OK  ] Started Postfix Mail Transport Agent.
    [  OK  ] Started Crash recovery kernel arming.
    [  OK  ] Created slice user-1000.slice.
    ==================================
    Instructing Cobbler to run Ansible
    ==================================
    [  OK  ] Created slice user-1100.slice.
         Starting Time & Date Service...
    [  OK  ] Started Time & Date Service.

Signed-off-by: David Galloway <dgallowa@redhat.com>

### CODE REVIEW

**Comment by zmc** [comment]
👍 nice!

**Comment by dmick** [comment]
maybe plus ", waiting for completion" ?

**Comment by djgalloway** [comment]
@dmick K.  Now output looks like (except "Waiting for completion" is centered):
    ==================================
    Instructing Cobbler to run Ansible
              Waiting for completion
    ==================================

**Comment by dmick** [comment]
schweet

**Pull request merged**
