### PR TITLE
Several bugs/usability things in smart.pl, and a new version with human output

### PR DESCRIPTION
**Pull request by dmick**

### CODE REVIEW

**Comment by zmc** [comment]
@dmick hrm, more Perl. I'm not sure who would be good to review this. I'm certainly no expert :)

**Comment by dmick** [comment]
yeah, like I am?  :)

**Comment by dmick** [comment]
hold off on this for a second, 1) need ot add the new script to the yml, and 2) fatfingered my manual merge into a syntax error

**Comment by dmick** [comment]
OK, smart-multiline.pl is fixed, and added to the yml list

**Pull request merged**
