### PR TITLE
teuthology: py3 for pulpito and paddles

### PR DESCRIPTION
**Pull request by kshtsk**
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@suse.com>

### CODE REVIEW

**Comment by kshtsk** [comment]
hey @djgalloway could you please take a look at this?

**Comment by kshtsk** [comment]
This might be dependent on corresponding pulpito PR https://github.com/ceph/pulpito/pull/80

**Review by djgalloway — APPROVED** [review]
LGTM

**Comment by kshtsk** [comment]
@djgalloway I do not have right to merge this

**Pull request merged**
