### PR TITLE
Updates to nagios disk monitoring script

### PR DESCRIPTION
**Pull request by djgalloway**
Adds support for magnas / non-raid systems
Adds support for nagios multiline output

Signed-off-by: dgalloway <dgallowa@REDHAT.COM>

### CODE REVIEW

**Comment by djgalloway** [comment]
See mira026 in nagios for sample Service output

**Comment by dmick** [comment]
this would be much better if we split it into logical chunks/commits by theme/fix/enhancement.  We can work together to do that if you like.

**Comment by zmc** [comment]
@dmick anything holding this back? Not sure if we want to block this on a rewrite, but if you feel strongly... ;)

**Comment by dmick** [comment]
I hadn't yet understood the answer to "why remove $scsi".  It makes sense now I think.  And bleh about the array counts; it just increases my desire to rewrite this.

**Pull request merged**
